version: '2'
services:
  mysql:
    container_name: my_mysql
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'secret' # TODO: Change this
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
  php:
    container_name: my_php
    restart: always
    image: tutum/apache-php
    ports:
      - "85:80"
    volumes:
      - ./app:/var/www/html